#CUDA_DIR := /usr/local/cuda
CUDA_DIR := /usr/local/cuda-8.0
#CPU_ONLY := 1
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
                -gencode arch=compute_35,code=sm_35 \
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_52,code=sm_52 \
                -gencode arch=compute_60,code=sm_60 \
                -gencode arch=compute_61,code=sm_61 \
                -gencode arch=compute_61,code=compute_61



#BLAS := atlas
BLAS := open

BLAS_LIB := /usr/lib64/atlas

HOME := /l/vision/v5/chen478
ANACONDA_HOME := $(HOME)/anaconda
PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
$(ANACONDA_HOME)/include/python2.7 \
$(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

PYTHON_LIB := $(ANACONDA_HOME)/lib

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib64

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

WITH_PYTHON_LAYER := 1
#OPENCV_VERSION := 3
# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0
#
# # enable pretty build (comment to see full commands)
Q ?= @
